### ISSUE TITLE
I can't compiling> fatal error: nfc/nfc.h: No such file or directory

### ISSUE THREAD

**Issue by amoeles** [aczid/crypto1_bs#10]
Hi, i use kali linux with libnfc preinstalled, when i try to compile crypto1_bs i get this error:

**libnfc_crypto1_crack.c:292:21: fatal error: nfc/nfc.h: No such file or directory**
compilation terminated.
Makefile:12: recipe for target 'all' failed

What can i do?

Thanks

**Comment by aczid** [comment]
Install libnfc-dev or libnfc-devel from your package manager, or use the [git version](https://github.com/nfc-tools/libnfc).

**Comment by amoeles** [comment]
Thank you for your great support aczid. With the latest version of Kali Linux libnfc is already installed, but I'll try your advice and i comment here the results. 
Thanks again aczid!

**Comment by amoeles** [comment]
I get not install successfully libnfc with kali so I will install ubuntu desktop 14.04 64bit to work with crypto1_bs , regards.

**Comment by amoeles** [comment]
Program compiled successfully under ubuntu desktop 14.04 64bit without any problem.

Thanks to aczid.

**Comment by aczid** [comment]
Happy to hear it, thanks for confirming that it works.

**Comment by amoeles** [comment]
Tested on Kali 2016.1 and works perfec too. 
Regards.
