### ISSUE TITLE
Merging libnfc_crypto1_crack into mfoc?

### ISSUE THREAD

**Issue by EmuAGR** [aczid/crypto1_bs#14]
Hi! I have some code to enhance mfoc in mind, and I plan to use this new algorithm but it should be machine-independent (as I need to compile it into an Intel Quark CPU for my undergraduate thesis). Do you think this is a good idea?

Thank you for this hard work! :)

**Comment by aczid** [comment]
Hello and sorry for the late reply. Updating MFOC sounds like a nice idea, but I'm afraid it will require a GPGPU implementation. Because of the fixed PRNG it is required to go through the whole 48 bit keyspace, and this seems infeasible on an embedded device like the Quark.

**Comment by aczid** [comment]
Please let me know you have had any progress in the past year and I'll reopen this issue.
