### ISSUE TITLE
libnfc_crypto1_crack terminates with SIGILL

### ISSUE THREAD

**Issue by DrSchottky** [aczid/crypto1_bs#18]
Compiling with -mpopcnt enabled by default makes program terminate with SIGILL if the cpu has not sse4/popcnt support.

**Comment by aczid** [comment]
Ok, let's fix it. https://github.com/aczid/crypto1_bs/commit/781c586b79aba492ea6c3c7a52f375b1c8879d40

**Comment by DrSchottky** [comment]
I added this to my Makefile to turn on automatically popcnt if supported by cpu
```
POPCNT_SUPPORT = $(shell /bin/grep -m 1 -o 'popcnt' /proc/cpuinfo)

ifneq (${POPCNT_SUPPORT},) 
    CFLAGS += -mpopcnt
endif
```
