### ISSUE TITLE
implementation of your latest work.

### ISSUE THREAD

**Issue by sumanblack666** [aczid/crypto1_bs#22]
Hi you've done a great work recently. Currently im using ACR122U and cracking a mifare 4k card using libnfc_crypto1_crack  , Can you help to implement your latest work " http://www.proxmark.org/forum/viewtopic.php?id=4873 " into this ? and can you help to do a automated to  command line to crack all the sectors by inputting one key ?

**Comment by aczid** [comment]
It's not my work, the new improvements are all by @piwi. I have been meaning to port it for libnfc, but haven't gotten very far. Feel free to give it a shot yourself. :)

**Comment by aczid** [comment]
Solved by https://github.com/vk496/mfoc/tree/hardnested
