### ISSUE TITLE
mfoc still fails with key found in crypto1_bs

### ISSUE THREAD

**Issue by emveeha** [aczid/crypto1_bs#23]
crypto1 cracks my keys just fine however when I feed one into mfoc it fails with the following message:
`mfoc: ERROR: No success, maybe you should increase the probes`

I have tried both an A and a B key.
 
I just need one cracked key right? 

The card is an sle66 emulating a MiFare Classic 4k.

**Comment by matthijsvh** [comment]
I started to crack the keys one by one  using crypto1.
I am stuck on getting key A of sector 36 (block 192).
I am able to crack the remaining sectors.

`Starting 4 threads to test 210560831668 states using 128-way bitslicing
Cracking...  99.88%
No solution found :(`

**Comment by emveeha** [comment]
I have succesfully dumped the A and B keys and have made a dump using MFOC.
Thank you for your work!

BTW: The card is an OV-chipkaart used by the dutch public transport system.
