### ISSUE TITLE
Inconsistent filenames

### ISSUE THREAD

**Issue by rapperskull** [aczid/crypto1_bs#27]
When running the libnfc_crypto1_crack program on a Mifare Classic tag with UID starting with 0, the filename is truncated: instead of "0x0fffffff_000A.txt" it is "0xfffffff_000A.txt". For consistency and better integration with other programs, the UID should always be printed in full length.

**Comment by aczid** [comment]
Fixed in https://github.com/aczid/crypto1_bs/commit/5818f369da46fa49268dae0cecf3f6f94a233722 .
Thanks!
