### ISSUE TITLE
craptev1-v1.1 Website down

### ISSUE THREAD

**Issue by hendl** [aczid/crypto1_bs#30]
Hi

The website http://crapto1.netgarage.org seems to be offline. 
Is there any other way to get these files?

thx

**Comment by aczid** [comment]
Duplicate of https://github.com/aczid/crypto1_bs/issues/29

**Comment by aczid** [comment]
Keeping this issue open for visibility.

**Comment by aczid** [comment]
Duplicate of https://github.com/aczid/crypto1_bs/issues/29

**Comment by pengxueting** [comment]
> Hi
> 
> The website http://crapto1.netgarage.org seems to be offline. Is there any other way to get these files?
> 
> thx

我也没找到
