### ISSUE TITLE
Error - doesn't look like the right key

### ISSUE THREAD

**Issue by eyJhb** [aczid/crypto1_bs#31]
I'm trying to recover the keys for a NFC tag, and have found the B key for all blocks of the device (works fine with mfoc, does not complain etc.), but as soon as I insert them into libnfc_crypto1_crack, as 

`libnfc_crypto1_crack <key> 60 B 60 A`

I get the following error

`Reader-answer transfer error, exiting.. <key> doesn't look like the right key B for block 60 (sector 15)`

And as stated, mfoc reads using the B key without complaining at all!

Any ideas or suggestions?

**Comment by dioxygene** [comment]
hi

i have the same error, i use a good key instead of <key>

Any ideas or suggestions?

**Comment by eyJhb** [comment]
@dioxygene something I did wrong, cannot remember what. Closing as this is not a issue.
