### ISSUE TITLE
offline crapto1.netgarage.org

### ISSUE THREAD

**Issue by cris76** [aczid/crypto1_bs#32]
I cant compile your project becouse crapto1.netgarage.org is offline.
pls can you send me CRAPTEV1 and CRAPTO1 libraries.
My mail is cripalcri@gmail.com
Thanks

**Comment by aczid** [comment]
Duplicate of https://github.com/aczid/crypto1_bs/issues/29

**Comment by pengxueting** [comment]
我也无法编译您的项目 crapto1.netgarage.org 处于离线状态。
请你把 CRAPTEV1 和 CRAPTO1 库发给我。另外我的nfc文件也打不开
我的邮件 [cripalcri@gmail.com](mailto:cripalcri@gmail.com)
谢谢
