### ISSUE TITLE
key truncated

### ISSUE THREAD

**Issue by tbox1911** [aczid/crypto1_bs#4]
Hi,

I was able to compile all three tools, but when I use "./solve_bs" the key is truncated and the first 2 byte is zeroed.

```
./solve_bs 0xcafec0de.txt 0xcafec0de
Initializing BS crypto-1
Using 64-bit bitslices
Bitslicing rollback byte: 1f...
Bitslicing nonces...
Starting 6 threads to test 1418412964 states
Found key: **0000**61003333
Tested 3523606116 states
```

when I use ./solve_piwi_bs or ./solve_piwi the key is correctly recovered.

do you have and idea of why ?

Best regards

**Comment by tbox1911** [comment]
I respond to myself

in file "solve_bs.c" line 29

change the line :
            printf("Found key: %012lx\n", key);
by :
            printf("Found key: %012"llx"\n", key);

Hope it helps

**Comment by iceman1001** [comment]
Yeah, I saw I missed that one in my previous commit. Fixed and added your -mmmx parameter in the latest PR.

**Comment by aczid** [comment]
Thanks for the report, @tbox1911 and addressing this, @iceman1001. Doesn't -mpopcnt imply SSE, which implies MMX? What required it?

**Comment by iceman1001** [comment]
isn't -mpopcnt only allowing for popcount functionality?  and mmx,sse,sse2,sse3 allows for those instructions aswell
On my ubuntu compiling with -msse2 -msse -mmmx gives really fast solving for the provided file.

**Comment by aczid** [comment]
I don't see how it would matter over using -mpopcnt, but if it works it works. :) Maybe it should be -march=native?

**Comment by iceman1001** [comment]
Try:
gcc -Og -mpopcnt -mmmx -msse -msse2 -std=c99 solve_piwi_bs.c crypto1_bs.c crypto1_bs_crack.c -Icraptev1-v1.0 craptev1-v1.0/craptev1.c crapto1-v3.3/crapto1.c -o solve_piwi_bs -lpthread

vs
gcc -Og -mpopcnt -std=c99 solve_piwi_bs.c crypto1_bs.c crypto1_bs_crack.c -Icraptev1-v1.0 craptev1-v1.0/craptev1.c crapto1-v3.3/crapto1.c -o solve_piwi_bs -lpthread

**Comment by aczid** [comment]
I measure no difference between these two on my i3 laptop, also -Og generates noticeably slower code than -Ofast / -O3.

**Comment by aczid** [comment]
Does -march=native give you the same performance as all those flags?

**Comment by iceman1001** [comment]
Test:
params | res
------------------
-o3 --mmmx -msse -msse2 -mpopcnt |  7.4 sec
-o3 -mpopcnt | 1.05 min   (plus compiler warnings)
-o3 -mpopcnt -march=native | 6.5sec
-----------------------

Sample of compiler warning:
crypto1_bs.c: In function ‘crypto1_bs_bit’:
crypto1_bs.c:46:1: warning: MMX vector return without MMX enabled changes the ABI [-Wpsabi]
 inline const bitslice_value_t crypto1_bs_bit(const bitslice_value_t input, const bool is_encrypted){

**Comment by iceman1001** [comment]
Might it be that your dev-env sets some flags per default?

**Comment by iceman1001** [comment]
You are right,  the -Og gives slower execution.

**Comment by iceman1001** [comment]
http://pastebin.com/TQ0g2DVq

By the looks of it,   I compared your three solvers,  and different comilations settings.
the bitsliced solver based on blapost's implementation seems to be a bit faster.
I didn't measure blaposts solver.

**Comment by aczid** [comment]
Ok, so we go with -O3 -mmmx -march=native ?

**Comment by iceman1001** [comment]
aha, but I think we still go for the "-O3 -mpopcnt -march=native" instead.

**Comment by aczid** [comment]
All in all it doesn't seem to matter that much, what *would* be interesting is seeing the performance on a machine with AVX2.

**Comment by iceman1001** [comment]
http://pastebin.com/ru3nY3TD
Interesting to see the procentages of the threads, but still your original setting plus -march=native is faster in a  test with key searchspace forced to 100% by giving wrong uid.

**Comment by iceman1001** [comment]
@aczid  I merged your patch into my fork. Needed some extra work for mingw but it looks like it compiles and works on both Mingw/Ubuntu14.04  now.    
Well, there is a minor bug with the reporting of time in the printouts.

**Comment by aczid** [comment]
Closing this issue, can open a new one about compiler flags at a later time if needed.
