### ISSUE TITLE
solve always get error

### ISSUE THREAD

**Issue by xtigmh** [aczid/crypto1_bs#41]
Some mifare card always send the same nt, so we can't crack this card?
libnfc_crypto1_crack will never stop for this type of card.
Here is contents of nonces.bin gathered by Proxmark3:
B94FDA1404008190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC228190C7DC8190C7DC22……

**Comment by aczid** [comment]
The attack can't work with a constant nonce. There is a thread about this problem [here](https://github.com/RfidResearchGroup/proxmark3/issues/133).

**Comment by xtigmh** [comment]
Thanks!

**Comment by xtigmh** [comment]
I study this card, the nonce is constant, there are only 2 nonces for all sector, distance is 160,so we only can get 32bit keystream.But nested auth attack needs 64 bit keystream.If only know 32 bits keystream,the candidate keys is between 2^15~2^17.Online bruteforce is also avaiable in 4 hours.
Has any idea to speedup?
proxmark3> hf mf nested o 0 a ffffffffffff 4 a
--nested. sectors: 1, block no:  0, key type:A, eml:n, dmp=n checktimeout=471 us
--target block no:  4, target key type:A
uid:295ad814 trgbl=4 trgkey=0
nt=7eef3586, ks1=ffff93b7
statelist[0].len=155091
after intersection:
statelist[0].len=155091
i=155090
Found valid key:ffffffffffff
