### ISSUE TITLE
illegal instruction (core dumped) error when running without AVX.

### ISSUE THREAD

**Issue by draand28** [aczid/crypto1_bs#42]
The tool doesn't work on older CPUs without AVX support. It always gives me this error: illegal instruction (core dumped) after collecting nonces. The CPUs I use do support SSE/SSE2 and SSSE3/SSE4_1/SSE4_2. Do I need to run a custom command in order to use SSE instruction set? The command I run is: ./libnfc_crypto1_crack c1e51c63b8f5 4 A 60 B.

**Comment by aczid** [comment]
Hi, the first few lines of the Makefile try to help you with this issue.
```
# if -march=native does not work on your platform, you could try
# -msse
# -msse2
# -mavx
# or
# -mavx2
```

Just try some of these options for the CFLAGS line in the Makefile to get it to build correctly on your machine.

**Comment by draand28** [comment]
Thank you! I used -msse2 and it fixed my problem.
