### ISSUE TITLE
compile error on gcc4.4.0

### ISSUE THREAD

**Issue by iceman1001** [aczid/crypto1_bs#6]
this row inside crypto1_bs.h

#define VECTOR_SIZE (MAX_BITSLICES/8)
typedef unsigned int __attribute__((aligned(VECTOR_SIZE))) __attribute__((vector_size(VECTOR_SIZE))) bitslice_value_t;

Gives troubles on a gcc4.4.0 env. 
::start snippet::
In file included from nonce2key/crypto1_bs.c:25:
nonce2key/crypto1_bs.h:25: error: alignment of array elements is greater than element size
make[1]: *** [obj/nonce2key/crypto1_bs.o] Error 1
make[1]: Leaving directory `/pm3/client'
make: *** [client/all] Error 2

**Comment by aczid** [comment]
I don't know what I did wrong here... Can I blame GCC? I can't easily reproduce the bug without your toolchain, and even then I no idea how to fix it.

**Comment by iceman1001** [comment]
https://github.com/Proxmark/proxmark3/wiki/Windows#development-environment-installation

Easy to get the toolchain used,  ;)  Finding a solution is harder.

**Comment by iceman1001** [comment]
Dropping this one. There is a option to download a docker container image instead, which will have ubuntu 14.04 trusty installed.  No need to run the old proxspace environment anymore.
